import { Router } from "express";

import faqRoutes from "../admin/faq/faq.routes";
import roomRoutes from "../admin/room/room.routes";
import blogRoutes from "../admin/blog/blog.routes";
import roleRoutes from "../admin/role/role.routes";
import userRoutes from "../public/user/user.routes";
import adminRoutes from "../admin/admin/admin.routes";
import bannerRoutes from "../admin/banner/banner.routes";
import couponRoutes from "../admin/coupon/coupon.routes";
import reviewRoutes from "../public/review/review.routes";
import priceRoutes from "../admin/pricing/pricing.routes";
import paymentRoutes from "../admin/payment/payment.routes";
import amenityRoutes from "../admin/amenity/amenity.routes";
import supportRoutes from "../public/support/support.routes";
import bookingRoutes from "../public/booking/booking.routes";
import galleryRoutes from "../public/gallery/gallery.routes";
import propertyRoutes from "../admin/property/property.routes";
import bookmarkRoutes from "../public/bookmark/bookmark.routes";
import stateCityRoutes from "../public/statecity/statecity.routes";
import FaqCategoryRoutes from "../admin/faqcategory/faqcategory.routes";
import testimonialRoutes from "../admin/testimonial/testimonial.routes";
import nearByPlacesRoutes from "../admin/nearbyplace/nearbyplace.routes";
import abusereportRoutes from "../public/abusereport/abusereport.routes";
import blogcategoryRoutes from "../admin/blogcategory/blogcategory.routes";
import subscriptionRoutes from "../admin/subscription/subscription.routes";
import useractivityRoutes from "../public/useractivity/useractivity.routes";
import cleaningRoutes from "../admin/cleaningschedule/cleaningschedule.routes";
import userpreferenceRoutes from "../public/userpreference/userpreference.routes";
import enrollmentRoutes from "../admin/bookingenrollment/bookingenrollment.routes";

const router = Router();

router.use("/faq", faqRoutes);
router.use("/room", roomRoutes);
router.use("/blog", blogRoutes);
router.use("/user", userRoutes);
router.use("/role", roleRoutes);
router.use("/price", priceRoutes);
router.use("/admin", adminRoutes);
router.use("/banner", bannerRoutes);
router.use("/coupon", couponRoutes);
router.use("/review", reviewRoutes);
router.use("/payment", paymentRoutes);
router.use("/amenity", amenityRoutes);
router.use("/support", supportRoutes);
router.use("/gallery", galleryRoutes);
router.use("/booking", bookingRoutes);
router.use("/bookmark", bookmarkRoutes);
router.use("/cleaning", cleaningRoutes);
router.use("/property", propertyRoutes);
router.use("/location", stateCityRoutes);
router.use("/enrollment", enrollmentRoutes);
router.use("/activity", useractivityRoutes);
router.use("/faqcategory", FaqCategoryRoutes);
router.use("/testimonial", testimonialRoutes);
router.use("/abusereport", abusereportRoutes);
router.use("/nearbyplaces", nearByPlacesRoutes);
router.use("/blogcategory", blogcategoryRoutes);
router.use("/subscriptionplan", subscriptionRoutes);
router.use("/userpreference", userpreferenceRoutes);

export default router;
