import { Router } from "express";

import faqRoutes from "../admin/faq/faq.routes";
import blogRoutes from "../admin/blog/blog.routes";
import knowledgeRoutes from "../public/knowledge/knowledge.routes";
import leadRoutes from "../admin/lead/lead.routes";
import roleRoutes from "../admin/role/role.routes";
import landerRoutes from "../lander/lander.routes";
import userRoutes from "../public/user/user.routes";
import adminRoutes from "../admin/admin/admin.routes";
import termsRoutes from "../admin/terms/terms.routes";
import cibilRoutes from "../public/cibil/cibil.routes";
import offerRoutes from "../public/offer/offer.routes";
import bannerRoutes from "../admin/banner/banner.routes";
import bankerRoutes from "../admin/banker/banker.routes";
import contestRoutes from "../admin/contest/contest.routes";
import refundRoutes from "../admin/refund/refund.routes";
import privacyRoutes from "../admin/privacy/privacy.routes";
import paymentRoutes from "../admin/payments/payment.routes";
import consentRoutes from "../public/consent/consent.routes";
import formSubmitClickRoutes from "../public/formSubmitClick/formSubmitClick.routes";
import supportRoutes from "../public/support/support.routes";
import referralRoutes from "../public/referral/referral.routes";
import documentsRoutes from "../public/documents/documents.routes";
import dashboardRoutes from "../admin/dashboard/dashboard.routes";
import loanQueryRoutes from "../public/loanquery/loanquery.routes";
import stateCityRoutes from "../public/statecity/statecity.routes";
import adminAgentChatRoutes from "../admin/chat/adminAgentChat.routes";
import bankProductRoutes from "../admin/bankProduct/bankProduct.routes";
import documentCatalogRoutes from "../admin/documentCatalog/documentCatalog.routes";
import FaqCategoryRoutes from "../admin/faqcategory/faqcategory.routes";
import testimonialRoutes from "../admin/testimonial/testimonial.routes";
import abusereportRoutes from "../public/abusereport/abusereport.routes";
import blogcategoryRoutes from "../admin/blogcategory/blogcategory.routes";
import insuranceQueryRoutes from "../public/insurancequery/insurancequery.routes";
import agentRoutes from "../public/agent/agent.routes";
import agencyRoutes from "../public/agency/agency.routes";

const router = Router();

router.use("/faq", faqRoutes);
router.use("/blog", blogRoutes);
router.use("/knowledge", knowledgeRoutes);
router.use("/user", userRoutes);
router.use("/role", roleRoutes);
router.use("/leads", leadRoutes);
router.use("/admin", adminRoutes);
router.use("/terms", termsRoutes);
router.use("/cibil", cibilRoutes);
router.use("/banner", bannerRoutes);
router.use("/bankers", bankerRoutes);
router.use("/contests", contestRoutes);
router.use("/offers", offerRoutes);
router.use("/lander", landerRoutes);
router.use("/support", supportRoutes);
router.use("/payments", paymentRoutes);
router.use("/location", stateCityRoutes);
router.use("/referrals", referralRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/loanquery", loanQueryRoutes);
router.use("/chat", adminAgentChatRoutes);
router.use("/documents", documentsRoutes);
router.use("/refund-policy", refundRoutes);
router.use("/privacy-policy", privacyRoutes);
router.use("/testimonial", testimonialRoutes);
router.use("/abusereport", abusereportRoutes);
router.use("/faqcategory", FaqCategoryRoutes);
router.use("/consent-history", consentRoutes);
router.use("/form-submit-clicks", formSubmitClickRoutes);
router.use("/bank-products", bankProductRoutes);
router.use("/document-catalog", documentCatalogRoutes);
router.use("/blogcategory", blogcategoryRoutes);
router.use("/insurancequery", insuranceQueryRoutes);
router.use("/agent", agentRoutes);
router.use("/agency", agencyRoutes);

export default router;
