import { Router } from "express";

import faqRoutes from "../admin/faq/faq.routes";
import blogRoutes from "../admin/blog/blog.routes";
import leadRoutes from "../admin/lead/lead.routes";
import roleRoutes from "../admin/role/role.routes";
import landerRoutes from "../lander/lander.routes";
import userRoutes from "../public/user/user.routes";
import adminRoutes from "../admin/admin/admin.routes";
import termsRoutes from "../admin/terms/terms.routes";
import cibilRoutes from "../public/cibil/cibil.routes";
import bannerRoutes from "../admin/banner/banner.routes";
import refundRoutes from "../admin/refund/refund.routes";
import privacyRoutes from "../admin/privacy/privacy.routes";
import paymentRoutes from "../admin/payments/payment.routes";
import supportRoutes from "../public/support/support.routes";
import dashboardRoutes from "../admin/dashboard/dashboard.routes";
import loanQueryRoutes from "../public/loanquery/loanquery.routes";
import stateCityRoutes from "../public/statecity/statecity.routes";
import adminAgentChatRoutes from "../admin/chat/adminAgentChat.routes";
import FaqCategoryRoutes from "../admin/faqcategory/faqcategory.routes";
import testimonialRoutes from "../admin/testimonial/testimonial.routes";
import abusereportRoutes from "../public/abusereport/abusereport.routes";
import blogcategoryRoutes from "../admin/blogcategory/blogcategory.routes";
import insuranceQueryRoutes from "../public/insurancequery/insurancequery.routes";

const router = Router();

router.use("/faq", faqRoutes);
router.use("/blog", blogRoutes);
router.use("/user", userRoutes);
router.use("/role", roleRoutes);
router.use("/leads", leadRoutes);
router.use("/admin", adminRoutes);
router.use("/terms", termsRoutes);
router.use("/cibil", cibilRoutes);
router.use("/banner", bannerRoutes);
router.use("/lander", landerRoutes);
router.use("/support", supportRoutes);
router.use("/payments", paymentRoutes);
router.use("/location", stateCityRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/loanquery", loanQueryRoutes);
router.use("/chat", adminAgentChatRoutes);
router.use("/refund-policy", refundRoutes);
router.use("/privacy-policy", privacyRoutes);
router.use("/faqcategory", FaqCategoryRoutes);
router.use("/testimonial", testimonialRoutes);
router.use("/abusereport", abusereportRoutes);
router.use("/blogcategory", blogcategoryRoutes);
router.use("/insurancequery", insuranceQueryRoutes);

export default router;
