import mongoose, { Schema, Document, Model } from "mongoose";

export interface IAmenity extends Document {
  name: string;
  icon?: string;
  category: string;
  createdAt?: Date;
  updatedAt?: Date;
  description?: string;
}

const AmenitySchema: Schema<IAmenity> = new Schema(
  {
    name: {
      type: String,
      required: [true, "Amenity name is required"],
      trim: true,
      unique: true,
      maxlength: 100,
      index: true,
    },
    icon: {
      type: String,
      trim: true,
      maxlength: 100,
    },
    category: {
      type: String,
      required: [true, "Amenity category is required"],
      trim: true,
      enum: [
        "luxury",
        "fitness",
        "entertainment",
        "technology",
        "wellness",
        "general",
        "fashion",
        "beauty",
        "food",
        "travel",
        "automotive",
        "sports",
        "gaming",
        "education",
        "business",
        "finance",
        "health",
        "lifestyle",
        "home",
        "garden",
        "pets",
        "books",
        "music",
        "art",
        "photography",
        "crafts",
        "outdoor",
        "adventure",
        "family",
        "parenting",
        "relationships",
        "career",
        "productivity",
        "science",
        "history",
        "culture",
        "politics",
        "news",
        "environment",
        "sustainability",
        "charity",
        "religion",
        "spirituality",
        "hobbies",
        "collectibles",
        "electronics",
        "software",
        "hardware",
        "mobile",
        "web",
        "social",
        "marketing",
        "design",
        "architecture",
        "real_estate",
        "construction",
        "manufacturing",
        "retail",
        "hospitality",
        "medical",
        "pharmaceutical",
        "legal",
        "consulting",
        "agriculture",
        "energy",
        "transportation",
        "logistics",
        "telecommunications",
        "media",
        "publishing",
        "broadcasting",
        "streaming",
        "events",
        "conferences",
        "workshops",
        "courses",
        "certifications",
        "tools",
        "equipment",
        "supplies",
        "materials",
        "services",
        "maintenance",
        "repair",
        "security",
        "insurance",
        "investment",
        "banking",
        "cryptocurrency",
        "shopping",
        "marketplace",
        "subscription",
        "membership",
        "community",
        "networking",
        "dating",
        "local",
        "international",
        "nonprofit",
        "government",
        "military",
        "emergency",
        "weather",
        "maps",
        "navigation",
        "reference",
        "utilities",
        "accessories",
        "seasonal",
        "holiday",
        "celebration",
        "specialty",
        "niche",
        "experimental",
        "beta",
        "premium",
        "budget",
        "discount",
        "vintage",
        "antique",
        "modern",
        "classic",
        "trending",
        "popular",
        "featured",
        "recommended",
        "custom",
        "personalized",
        "professional",
        "consumer",
        "industrial",
        "commercial",
        "residential"
      ]
    },
    description: {
      type: String,
      trim: true,
      maxlength: 300,
    },
  },
  {
    timestamps: true, // Automatically manage createdAt and updatedAt
  }
);

AmenitySchema.index({ category: 1 });

export const AmenityModel: Model<IAmenity> = mongoose.model<IAmenity>("Amenity", AmenitySchema);
